classDiagram
class GameManager {
  
  %% attributes

  - player : Player
  - saveSystem : SaveSystem
  - lastSaveTime : DateTime
  - upgrades : List&lt;Upgrade&gt;
  - achievements : List&lt;Achievement&gt;

  %% methods

  %% getters

  + getPlayer() : Player
  + getSaveSystem() : SaveSystem
  + getLastSaveTime() : DateTime
  + getUpgrades() : List&lt;Upgrade&gt;
  + getAchievements() : List&lt;Achievement&gt;

  %% setters

  + setPlayer(Player player) : void
  + setSaveSystem(SaveSystem saveSystem) : void
  + setLastSaveTime(DateTime lastSaveTime) : void
  + setUpgrades(List<Upgrade> upgrades) : void
  + setAchievements(List<Achievement> achievements) : void
  
  %% other
  
  + saveGame() : void
  + loadGame() : void
  + resetGame() : void
  + calculateOfflineProgress() : float
  + addCurrency(Currency currency, float amount) : void
  + spendCurrency(Currency currency, float amount) : void
  + applyUpgrade(Upgrade upgrade) : void
  + unclockAchievement(Achievement achievement) : void
}
